SKILL_NAME_MAX_LENGTH = 124
PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_OPEN = "В процессе"
PROJECT_STATUS_CLOSED = "Закончен"
PROJECT_STATUS_CHOICE = [
    (PROJECT_STATUS_OPEN, "В процессе"),
    (PROJECT_STATUS_CLOSED, "Закончен"),
]
PROJECT_STATUS_MAX_LENGTH = max(
    len(PROJECT_STATUS_OPEN),
    len(PROJECT_STATUS_CLOSED)
)

FORM_PROJECT_DESCRIPTION_ROWS = 4

PROJECTS_PER_PAGE = 12
SKILL_AUTOCOMPLETE_LIMIT = 10
