SKILL_NAME_MAX_LENGTH = 124
PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_OPEN = "Open"
PROJECT_STATUS_CLOSED = "Closed"
PROJECT_STATUS_CHOICE = [
    (PROJECT_STATUS_OPEN, "В процессе"),
    (PROJECT_STATUS_CLOSED, "Закончен"),
]
PROJECT_STATUS_MAX_LENGTH = len(max(
    [max(i, key=len) for i in PROJECT_STATUS_CHOICE],
    key=len
))

FORM_PROJECT_DESCRIPTION_ROWS = 4

PROJECTS_PER_PAGE = 12
SKILL_AUTOCOMPLETE_LIMIT = 10
