# Generated by Django 5.2.4 on 2026-06-05 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=79999999999, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: "+7XXXXXXXXXX"', regex='^\\+7\\d{10}$')]),
            preserve_default=False,
        ),
    ]
