# Generated by Django 5.2.4 on 2026-06-05 09:44

import users.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to=users.constants.AVATAR_PATH),
        ),
    ]
