# Generated by Django 5.2.4 on 2026-06-05 10:10

import users.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=users.constants.AVATAR_PATH),
        ),
    ]
