# Generated by Django 5.2.4 on 2026-06-05 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email', 'surname', 'name']},
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='^https://github.com/[\\w\\-]+/?$')], verbose_name='Ссылка на профиль GitHub'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='В сети'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=124, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: "+7XXXXXXXXXX"', regex='^\\+7\\d{10}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=124, verbose_name='Фамилия'),
        ),
    ]
