# Generated by Django 5.2.4 on 2026-06-04 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('github_url', models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Ссылка на репозиторий проекта', regex='^https://github.com/[\\w\\-]+/[\\w\\-]+/?$')])),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='users.user')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_projects', to='users.user')),
                ('skills', models.ManyToManyField(blank=True, related_name='projects', to='projects.skill')),
            ],
        ),
    ]
