# Generated by Django 5.2.4 on 2026-06-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_skill_options_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('В процессе', 'В процессе'), ('Закончен', 'Закончен')], default='В процессе', max_length=10, verbose_name='Статус'),
        ),
    ]
